export const pokemonTypes = [
  {
    name: 'normal',
    name_pt: 'normal',
    bg_color: '#e397a7',
    url: 'https://pokeapi.co/api/v2/type/1/',
  },
  {
    name: 'fighting',
    name_pt: 'lutador',
    bg_color: '#ff6337',
    url: 'https://pokeapi.co/api/v2/type/2/',
  },
  {
    name: 'flying',
    name_pt: 'voador',
    bg_color: '#82b5cf',
    url: 'https://pokeapi.co/api/v2/type/3/',
  },
  {
    name: 'poison',
    name_pt: 'veneno',
    bg_color: '#a767df',
    url: 'https://pokeapi.co/api/v2/type/4/',
  },
  {
    name: 'ground',
    name_pt: 'terra',
    bg_color: '#bb7221',
    url: 'https://pokeapi.co/api/v2/type/5/',
  },
  {
    name: 'rock',
    name_pt: 'pedra',
    bg_color: '#9a3b1f',
    url: 'https://pokeapi.co/api/v2/type/6/',
  },
  {
    name: 'bug',
    name_pt: 'inseto',
    bg_color: '#049143',
    url: 'https://pokeapi.co/api/v2/type/7/',
  },
  {
    name: 'ghost',
    name_pt: 'fantasma',
    bg_color: '#986592',
    url: 'https://pokeapi.co/api/v2/type/8/',
  },
  {
    name: 'steel',
    name_pt: 'ferro',
    bg_color: '#52746f',
    url: 'https://pokeapi.co/api/v2/type/9/',
  },
  {
    name: 'fire',
    name_pt: 'fogo',
    bg_color: '#ff465c',
    url: 'https://pokeapi.co/api/v2/type/10/',
  },
  {
    name: 'water',
    name_pt: 'água',
    bg_color: '#71abfd',
    url: 'https://pokeapi.co/api/v2/type/11/',
  },
  {
    name: 'grass',
    name_pt: 'grama',
    bg_color: '#04ca40',
    url: 'https://pokeapi.co/api/v2/type/12/',
  },
  {
    name: 'electric',
    name_pt: 'elétrico',
    bg_color: '#e3e500',
    url: 'https://pokeapi.co/api/v2/type/13/',
  },
  {
    name: 'psychic',
    name_pt: 'psíquico',
    bg_color: '#ff1496',
    url: 'https://pokeapi.co/api/v2/type/14/',
  },
  {
    name: 'ice',
    name_pt: 'gelo',
    bg_color: '#cdeffd',
    url: 'https://pokeapi.co/api/v2/type/15/',
  },
  {
    name: 'dragon',
    name_pt: 'dragão',
    bg_color: '#018b96',
    url: 'https://pokeapi.co/api/v2/type/16/',
  },
  {
    name: 'dark',
    name_pt: 'sombrio',
    bg_color: '#58587c',
    url: 'https://pokeapi.co/api/v2/type/17/',
  },
  {
    name: 'fairy',
    name_pt: 'fada',
    bg_color: '#ff0c67',
    url: 'https://pokeapi.co/api/v2/type/18/',
  },
  {
    name: 'unknown',
    name_pt: 'desconhecido',
    bg_color: '#b2b363',
    url: 'https://pokeapi.co/api/v2/type/10001/',
  },
  {
    name: 'shadow',
    name_pt: 'sombra',
    bg_color: '#959497',
    url: 'https://pokeapi.co/api/v2/type/10002/',
  },
];
